---CREATES A NEW DIVISION TYPE E.g PRIMEAR LEAGUE,DIVISION 1,2,
CREATE TABLE "DivisionType"(
"DivisionTypeId" SERIAL NOT NULL PRIMARY KEY,
"Name" CHARACTER VARYING(500),
"Description" CHARACTER VARYING(1000))

---CREATE A NEW CLUB TABLE
CREATE TABLE "Team"(
"TeamId" BIGSERIAL NOT NULL PRIMARY KEY,
"TeamCode" CHARACTER VARYING(500) NOT NULL,
"ShortHand" CHARACTER VARYING(10) NOT NULL,
"ClubName" CHARACTER VARYING(1000) NOT NULL,
"Slogan" CHARACTER VARYING(200) NOT NULL,
"Email" CHARACTER VARYING(500) NOT NULL,
"PhoneNumber" CHARACTER VARYING(20) NOT NULL,
"Website" CHARACTER VARYING(200) NOT NULL,
"DivisionTypeId" INT NOT NULL,FOREIGN KEY("DivisionTypeId") REFERENCES "DivisionType"("DivisionTypeId"),
"CreatedDate" TIMESTAMP WITHOUT TIME ZONE)

---Add colors 
CREATE TABLE "Color"(
"ColorId" SERIAL NOT NULL PRIMARY KEY,
"Type" CHARACTER VARYING(500) NOT NULL,
"CreatedDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL)

--CLUB KIT
CREATE TABLE "Clubkit"(
"ClubKitId" SERIAL NOT NULL PRIMARY KEY,
"TeamId" BIGSERIAL NOT NULL,FOREIGN KEY("TeamId") REFERENCES "Team"("TeamId"),
"BrandName" CHARACTER VARYING(1000) NOT NULL,
"KitType" SERIAL NOT NULL,
"ColorId" SERIAL NOT NULL,FOREIGN KEY("ColorId") REFERENCES "Color"("ColorId"),
"CreatedDate" TIMESTAMP WITHOUT TIME ZONE)

CREATE TABLE "ClubPartner"(
"ClubPartnerIdId" SERIAL NOT NULL PRIMARY KEY,
"TeamId" BIGSERIAL NOT NULL,FOREIGN KEY("TeamId") REFERENCES "Team"("TeamId"),
"BrandName" CHARACTER VARYING(1000) NOT NULL,
"Duration" SERIAL NOT NULL,
"SignedDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
"CreatedDate" TIMESTAMP WITHOUT TIME ZONE)

CREATE TABLE "SocialMediaHandler"(
"SocialMediaHandlerId" SERIAL NOT NULL PRIMARY KEY,
"TeamId" BIGSERIAL NOT NULL,FOREIGN KEY("TeamId") REFERENCES "Team"("TeamId"),
"AccountType" CHARACTER VARYING(200) NOT NULL,
"HandlerUrl" CHARACTER VARYING(1000) NOT NULL,
"CreatedDate" TIMESTAMP WITHOUT TIME ZONE)

CREATE TABLE "TeamLogin"(
"TeamLoginId" SERIAL NOT NULL PRIMARY KEY,
"TeamId" BIGSERIAL NOT NULL,FOREIGN KEY("TeamId") REFERENCES "Team"("TeamId"),
"Email" CHARACTER VARYING(1000) NOT NULL,
"PhoneNumber" CHARACTER VARYING(20) NOT NULL,
"Password" TEXT NOT NULL,
"CreatedDate" TIMESTAMP WITHOUT TIME ZONE)

CREATE TABLE "TeamImage"(
"ImageId" SERIAL NOT NULL PRIMARY KEY,
"TeamId" BIGSERIAL NOT NULL,FOREIGN KEY("TeamId") REFERENCES "Team"("TeamId"),
"ImageUrl" CHARACTER VARYING(1000) NOT NULL,
"ImageBlob" CHARACTER VARYING(1000) NOT NULL,
"CreatedDate" TIMESTAMP WITHOUT TIME ZONE)

CREATE TABLE "Stadium"(
"StadiumId" SERIAL NOT NULL PRIMARY KEY,
"TeamId" BIGSERIAL NOT NULL,FOREIGN KEY("TeamId") REFERENCES "Team"("TeamId"),
"Name" CHARACTER VARYING(1000) NOT NULL,
"Capacity" CHARACTER VARYING(1000) NOT NULL,
"BuiltDate" TIMESTAMP WITHOUT TIME ZONE,
"Location" CHARACTER VARYING(1000) NOT NULL,
"CreatedDate" TIMESTAMP WITHOUT TIME ZONE)